# HTTP request test
# Work in Visual Studio Code with https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
# Login
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
	"username": "root",
	"password": "roO7p4s5wOrD"
}

###
# Get me
GET http://localhost:3000/me HTTP/1.1

###
# Get corpus
GET http://localhost:3000/corpus HTTP/1.1

###
# Post Layer
POST http://localhost:3000/corpus/5a136cbc4cac0b0001259df1/layer HTTP/1.1
content-type: application/json

{
	"name": "test",
	"description": {},
	"fragment_type": {},
	"data_type": {},
	"annotations": []
}